### PR TITLE
 Created React app - started navbar

### PR DESCRIPTION
**Pull request by BBoutet1**
I created the React app inside "client" folder.
To run the React application through VS code, go into "client" and run CL "npm start"

### CODE REVIEW

**Review by rishFilet — APPROVED** [review]

**Comment by gh0stl0nely** [comment]
@BBoutet1  I think we should wait for Henlin and Rishi to get the Gatsby template first then we can all work on the base code once they uploaded afterwards.

**Comment by BBoutet1** [comment]
I think templates are one page app to add. At least I can move on while waiting. Probably I won't use template navbar.

**Review by dghazi12 — APPROVED** [review]
Everything looks good. I would like to make just one minor comment regarding unnecessary files. Not a big deal at all but I don't see files like Favicon.ico, Logo.png files, Robots.txt etc. being used anywhere in the application. Maybe I missed something but if not I think they should be deleted on the next push to avoid confusion.

**Comment by gh0stl0nely** [comment]
I would suggest to pull from the latest gatsby template that Henlin and Saint pushed yesterday and added your code onto it. It seems to me that gatsby app involves a lot of different configuration compared to a traditional create-react-app.

**Comment by airshiprook** [comment]
Khoi is on the mark, please use the other repo (TTM-Gatsby) to continue your work, it indeed is very different from create-react-app!

**Comment by BBoutet1** [comment]
Ok. I will do thst!

**Pull request closed without merging**
